// <auto-generated />
using System;
using Test.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Test.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test.Domain.BranchMaster", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"), 1L, 1);

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BranchName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Circle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Network")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Region")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("State")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Zone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Test.Domain.KioskMaster", b =>
                {
                    b.Property<int>("KioskMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KioskMasterId"), 1L, 1);

                    b.Property<string>("AD_Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AntivirusInfo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BOFD_Route_No")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Bank_Route_No")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("BranchID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CTS_VendorType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FileUploadURL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Grid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IFSC_Code")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("InstallationStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("KioskID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("KioskSerialNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Location")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MACAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MachineIP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MyCustomColumn")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OSPatchVersion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OSType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("KioskMasterId");

                    b.HasIndex("BranchID");

                    b.ToTable("Kiosks");
                });

            modelBuilder.Entity("Test.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EmailID")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserType")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Test.Domain.VendorMaster", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"), 1L, 1);

                    b.Property<string>("ContactNo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EmailID")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TollFreeEmailID")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TollFreeNo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Test.Domain.KioskMaster", b =>
                {
                    b.HasOne("Test.Domain.BranchMaster", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
